services:
  - type: web
    name: article-summary
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd backend && python server.py
    envVars:
      - key: IS_PRODUCTION
        value: "true"
      - key: BASE_DIR
        value: /opt/render/project/src
    disk:
      name: data
      mountPath: /data
      sizeGB: 1 
