services:
  - type: web
    name: article-summary
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd backend && python server.py
    envVars:
      - key: FTIMES_BASE_DIR
        value: /data/ftimes
      - key: ECONOMIST_BASE_DIR
        value: /data/economist
    disk:
      name: data
      mountPath: /data
      sizeGB: 1 
